services:
  astro:
    image: node:iron
    container_name: prpb-astro
    restart: unless-stopped
    ports:
      - "43210:43210"
    working_dir: /home/node/app
    user: node
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    volumes:
      - ./:/home/node/app:rw
      - ./.env.local:/home/node/app/.env.development
    networks:
      - prpb

networks:
  prpb:
    name: prpb
    driver: bridge
