sonar.projectKey=Peerapon966_PRPB
sonar.organization=peerapon966
sonar.projectName=PRPB
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/*.png,**/*.jpg,**/*.jpeg,**/*.gif,**/*.webp,**/*.ico