name: "Deploy"
description: "Deploy application (Terraform and build artifacts) to AWS"
inputs:
  s3-bucket-name:
    description: "Terraform remote state S3 bucket name"
    required: true
  dynamodb-table-name:
    description: "Terraform remote state DynamoDB table name"
    required: true
  region:
    description: "AWS Region where Terraform remote state S3 bucket and DynamoDB table exist"
    required: true
  workspace:
    description: "Terraform workspace name to deploy resources"
    required: true
  tfvars-file:
    description: "Path to the tfvars file to use (relative to the terraform directory)"
    required: true
  db-connection-string:
    description: "Connection string for accessing database"
    required: true
  base-ref-sha:
    description: "Reference base commit SHA-256 (used for comparing file diff between 2 commits)"
    required: false
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Deploy application
      id: deploy
      run: deploy.sh
      shell: bash
      working-directory: ${{ github.workspace }}/terraform
      env:
        S3_BUCKET_NAME: ${{ inputs.s3-bucket-name }}
        DYNAMODB_TABLE_NAME: ${{ inputs.dynamodb-table-name }}
        REGION: ${{ inputs.region }}
        WORKSPACE: ${{ inputs.workspace }}
        TFVARS_FILE: ${{ inputs.tfvars-file }}
        DB_CONNECTION_STRING: ${{ inputs.db-connection-string }}
        BASE_REF_SHA: ${{ inputs.base-ref-sha }}