name: "Deploy"
description: "Deploy application (Terraform and build artifacts) to AWS"
inputs:
  workspace:
    description: "Terraform workspace name to deploy resources"
    required: true
  environment:
    description: "Target environment to deploy resources and application (workflow will use file 'tfvars/<environment>.tfvars' when deploying Terraform)"
    required: true
  db-connection-string:
    description: "Connection string for accessing backend database"
    required: true
  base-ref-sha:
    description: "Base/reference commit SHA-256"
    required: false
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Deploy application
      id: deploy
      run: deploy.sh
      shell: bash
      working-directory: ${{ github.workspace }}/terraform
      env:
        WORKSPACE: ${{ inputs.workspace }}
        ENVIRONMENT: ${{ inputs.environment }}
        DB_CONNECTION_STRING: ${{ inputs.db-connection-string }}
        BASE_REF_SHA: ${{ inputs.base-ref-sha }}
