CREATE TABLE IF NOT EXISTS blog_tags (
  blog_id INTEGER REFERENCES blogs(id) ON DELETE CASCADE NOT NULL,
  tag_id INTEGER REFERENCES tags(id) ON DELETE CASCADE NOT NULL,
  PRIMARY KEY (blog_id, tag_id),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);
