name: Deploy
run-name: Deploy new commit '${{ github.head_ref }}' (${{ github.sha }}) to ${{ inputs.environment || 'staging' }} environment

on:
  pull_request:
    branches: [main]
    types: [closed]
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        type: environment
        required: true
      base-ref-sha:
        description: "Base/reference commit SHA-256"
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  setup:
    if: startsWith(github.head_ref, 'dependabot/') == false
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.set-short-sha.outputs.short_sha }}
      branch_name: ${{ steps.sanitize-branch-name.outputs.branch_name }}
    steps:
      - name: Set short commit SHA
        id: set-short-sha
        run: echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
        # The artifact name cannot include these characters: Double quote ", Colon :, Less than <, Greater than >, Vertical bar |, Asterisk *, Question mark ?, Carriage return \r, Line feed \n, Backslash \, Forward slash /
      - name: Sanitize branch name
        id: sanitize-branch-name
        run: |
          raw="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}"
          echo "branch_name=$(echo "$raw" | sed 's/["<>:|*?\\\/\r\n]/_/g')" >> "$GITHUB_OUTPUT"
        
  build:
    needs: 
      - setup
    if: |
      needs.setup.result == 'success' &&
      (github.event.pull_request.merged == true ||
      github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'staging' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Set environment variable
        run: export $(grep -v '^#' .env.${{ inputs.environment || 'staging' }} | xargs)
      - name: Cache dependencies
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build -- --mode=${{ inputs.environment || 'staging'}}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: astro-build_${{ needs.setup.outputs.branch_name }}#${{ needs.setup.outputs.short_sha }}
          path: dist/
          retention-days: 7
          if-no-files-found: error
          overwrite: true
  deploy:
    needs:
      - setup
      - build
    if: needs.setup.result == 'success' && needs.build.result == 'success'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'staging' }}
    timeout-minutes: 60
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.TF_REMOTE_STATE_REGION }}
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: astro-build_${{ needs.setup.outputs.branch_name }}#${{ needs.setup.outputs.short_sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ github.workspace }}/dist
      - name: Deploy Application
        uses: ./.github/actions/deploy
        with:
          s3-bucket-name: ${{ vars.TF_REMOTE_STATE_S3_BUCKET }}
          dynamodb-table-name: ${{ vars.TF_REMOTE_STATE_DYNAMODB_TABLE }}
          region: ${{ vars.TF_REMOTE_STATE_REGION }}
          workspace: ${{ vars.TF_WORKSPACE }}
          environment: ${{ inputs.environment || 'staging' }}
          db-connection-string: ${{ secrets.DB_CONNECTION_STRING }}
          base-ref-sha: ${{ inputs.base-ref-sha }}