name: Test
run-name: Build and test '${{ github.head_ref }}' (${{ github.sha }})

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

# Specify target environment to run this workflow
env:
  TARGET_ENV: staging

jobs:
  # Propagate TARGET_ENV variable and other data to other jobs by its output
  setup:
    if: startsWith(github.head_ref, 'dependabot/') == false
    runs-on: ubuntu-latest
    outputs:
      target_env: ${{ steps.set-target-env.outputs.target_env }}
      short_sha: ${{ steps.set-short-sha.outputs.short_sha }}
      branch_name: ${{ steps.sanitize-branch-name.outputs.branch_name }}
    steps:
      - name: Set target environment
        id: set-target-env
        run: echo "target_env=${{ env.TARGET_ENV }}" >> $GITHUB_OUTPUT
      - name: Set short commit SHA
        id: set-short-sha
        run: echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
        # The artifact name cannot include these characters: Double quote ", Colon :, Less than <, Greater than >, Vertical bar |, Asterisk *, Question mark ?, Carriage return \r, Line feed \n, Backslash \, Forward slash /
      - name: Sanitize branch name
        id: sanitize-branch-name
        run: |
          raw="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}"
          echo "branch_name=$(echo "$raw" | sed 's/["<>:|*?\\\/\r\n]/_/g')" >> "$GITHUB_OUTPUT"
        
  test:
    needs: 
      - setup
    if: needs.setup.result == 'success'
    runs-on: ubuntu-latest
    environment: ${{ needs.setup.outputs.target_env }}
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Cache dependencies
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run unit tests
        run: npm run test:unit -- --mode=${{ needs.setup.outputs.target_env }}
      - name: Upload unit test report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report_${{ needs.setup.outputs.branch_name }}#${{ needs.setup.outputs.short_sha }}
          path: test-results/
          retention-days: 7
          overwrite: true
      - name: Run E2E tests
        run: npm run test:e2e
      - name: Upload E2E test report
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-report_${{ needs.setup.outputs.branch_name }}#${{ needs.setup.outputs.short_sha }}
          path: playwright-report/
          retention-days: 7
          overwrite: true
  build:
    needs:
      - setup
      - test
    if: needs.setup.result == 'success' && needs.test.result == 'success'
    runs-on: ubuntu-latest
    environment: ${{ needs.setup.outputs.target_env }}
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Set environment variable
        run: export $(grep -v '^#' .env.${{ needs.setup.outputs.target_env }} | xargs)
      - name: Cache dependencies
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build -- --mode=${{ needs.setup.outputs.target_env }}